#General site settings
title: Romina Rivadeneira
email: rivrom18@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Programmer | Entertainer | Sushi Lover
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: RomiRiv
github_username:  rrivaden03

#---------------------
# MENU LIST
menu:
  - {name: About Me, url: '#about'}
  - {name: Projects, url: '#projects'}
  - {name: Resume, url: '#'}
  - {name: Contact, url: '#contact'}


#---------------------
# ABOUT SECTION

blurb: <p>Hi! I am Romina, a Computer Engineer graduated from Iowa State University currently working at
  Radio Systems Corporation in Knoxville, TN. My main focus is developing firmware and software solutions with the
  Internet of Things software team at the company. Lastly, if you are remotely curious, RSC is a pet technology company and has
  little to do with radios.</p>
  <p>When I am not coding for the better good, I'm most likely searching for the
  best photo to take, best scene to draw, best story to read or best film to watch.</p>

skills:
- {name: Embedded (C + FreeRTOS), value: '9'}
- {name: Internet of Things (AWS), value: '9'}
- {name: Mobile Development, value: '7'}
- {name: Web Development, value: '6'}
- {name: Self-Motivation, value: '10'}
- {name: Communication and Empathy, value: '9'}
- {name: Problem-Solving, value: '8'}
- {name: Patience, value: '10'}


#-------------------------
# PROJECT section
projects:
  - {name: Connected Pet Products, folder: 'proj-1'}
  - {name: Miniature Greenhouses, folder: 'proj-2'}
  - {name: Bike-Share, folder: 'proj-3'}
  - {name: Aptus, folder: 'proj-4'}
  # - {name: Personal Website, folder: 'proj-5'}
  # - {name: ISSO Website, folder: 'proj-6'}
  # - {name: Miniature Greenhouses, folder: 'proj-7'}
  # - {name: Miniature Greenhouses, folder: 'proj-8'}

  #-------------------------
# CONTACT section
social:
  - {icon: twitter, link: 'https://twitter.com/RomiRiv'}
  - {icon: github, link: 'https://github.com/rrivaden03'}
  - {icon: 'linkedin', link: 'https://www.linkedin.com/in/rrivaden/'}
  - {icon: 'youtube', link: '#'}
  - {icon: 'twitch', link: 'https://www.twitch.tv/rrivaden03'}
